names:
- Jarrett
- Oscar
- Peter
- Nathan
- John
- James
- Mike
- Steven
- Christoph
- David
- Daniel
- Jason
- Jordan
- Eric
- Toby
- George
- Matthew
messages:
  chat: '<%name%> %message%'
  ask-item: 'Has anyone got %amount% %item%?'
bots:
  work-area: 100
  log-activity: false
  goals:
  - 64;LOG
  - 64;COBBLESTONE